### ISSUE TITLE
Binary channel mask scale/ mesh creation issues

### ISSUE THREAD

**Issue by hcamkerr** [VeinsOfTheEarth/RivGraph#92] opened 2023-01-05 13:40 UTC
Hi all, I'm trying to create a binary channel mask for a river in Alaska to run through RivGraph. I have created two channel masks - initially, I created one using the NAD 1927 Albers coordinate system, but then decided that using UTM Zone 6N was more appropriate, so created a mask with this CRS too. The binary channel masks covers an area of approximately 25 square km and are at 10m resolution, in 2-Bit TIFF format.

The issue I'm having is slightly different for both of the masks. For the original NAD Albers one, the code runs successfully up until the mesh creation section, where I get a shapely error (despite being on version 1.7.1). The error says _"NotImplementedError: Multi-part geometries do not provide a coordinate sequence"._ I also get this error with the UTM mask, although there seems to be other issues with this one too. There is an issue with the scales where 'Instantiate River Mask' shows the river reaching a scale of 500 x 400, which then shrinks to 500 x 300 at the 'Skeletonization' step. The network and nodes are also stretched across the binary mask and in totally the wrong place. I suspected this was due to NoData cells in the binary mask, but I can't seem to find any so I'm not sure what is causing all these scale problems. See images below.

![Screenshot 2023-01-05 133731](https://user-images.githubusercontent.com/122028727/210793027-09bba0d3-5785-4d5c-9180-8d712262bc1f.png)
![Screenshot 2023-01-05 133746](https://user-images.githubusercontent.com/122028727/210793030-1c014c30-6f82-49f6-8e76-62b810a5602b.png)
![Screenshot 2023-01-05 133758](https://user-images.githubusercontent.com/122028727/210793032-f534be7d-d686-4baa-b78b-cb524e0ef077.png)

I'm currently on a Windows computer, but also have a Mac I can test things on. I'm using the following package versions:

- conda=4.10.1
- python=3.9.15
- geopandas=0.9.0 (I was getting a GeoDataFrame error with the latest version)
- scikit-image=0.19.3
- opencv=4.5.5
- networkx=2.6.3
- shapely=1.7.1
- matplotlib=3.6.2
- fastdtw=0.3.4
- loguru=0.6.0
- scipy=1.8.1
- numpy=1.22.4

I have tried creating multiple masks in the UTM Zone 6N coordinate system, some with 2m resolution, and still getting the same issues.

Any advice or help on this would be hugely appreciated.  

Thank you!

**Comment by jonschwenk** [comment] 2023-01-05 21:55
Hi @hcamkerr , could you post a link to your georeferenced masks as well?

**Comment by hcamkerr** [comment] 2023-01-06 11:11
Hi @jonschwenk, zip file attached. Masks also available on Google Drive here:

https://drive.google.com/drive/folders/1RJM8Ik46nvAX1bOkKpV18LM8S70fTdTr?usp=sharing

[Binary_channel_masks.zip](https://github.com/VeinsOfTheEarth/RivGraph/files/10359587/Binary_channel_masks.zip)

**Comment by jonschwenk** [comment] 2023-01-06 20:34
Seems there are two issues (one per mask) here: UTM and I'll call the other one ESRI.

I will make a second post for the ESRI mask, here is what I found/did for the UTM mask.

For the UTM mask, here is some code and results for me:

```
from rivgraph.classes import river

name = 'issue92_utm'
path_to_mask = "X:\Research\RivGraph\Bugs\Issue 92\masks\Alaska_channel_mask_UTM.tif"
results_folder = r'X:\Research\RivGraph\Bugs\Issue 92\results'
es = 'NS'
alaska = river(name, path_to_mask, results_folder=results_folder, exit_sides=es, verbose=True)

alaska.skeletonize()
alaska.compute_network()
alaska.prune_network()
alaska.plot('network')
```
which yields

![image](https://user-images.githubusercontent.com/14874485/211052175-9cd4314f-0242-4ab1-8b03-d608c2e92966.png)

This appears correct to me, and I am unable to reproduce your shown plot for the UTM mask. However, when I run `alaska.assign_flow_directions()`, there were errors.

The main problem here is that the (default) mesh generation function in RivGraph is not actually designed for single-thread channels, but wider, braided rivers. Without getting into the details too much, usually in single-thread analysis, you are looking for a mesh or transects that follow the bends of that river. In the braided river case, you are following the channel belt, not a single channel. In practice, the difference amounts to really high curvature centerline (single-threaded) vs relatively low curvature valleyline (braided river), and high curvatures make meshing different.

RivGraph does have a function called `centerline_mesh` that is uncalled in any of the core functionality. I just committed edits that adapt this function to be used in the core functionality (i.e. class function calls like `assign_flow_directions`) based on a `single_thread` keyword you can now provide when instantiating the class (code below so don't worry if that doesn't make sense).

Here is a code sample and results:

from rivgraph.classes import river
import matplotlib.pyplot as plt

```
from rivgraph.classes import river
import matplotlib.pyplot as plt

name = 'issue92_utm'
path_to_mask = "X:\Research\RivGraph\Bugs\Issue 92\masks\Alaska_channel_mask_UTM.tif"
results_folder = r'X:\Research\RivGraph\Bugs\Issue 92\results'
es = 'NS'
# Note the new single_thread parameter!
alaska = river(name, path_to_mask, results_folder=results_folder, exit_sides=es, verbose=True, single_thread=True)
alaska.skeletonize()
alaska.compute_network()
alaska.compute_mesh() # here you can specify the spacing between transects (grid_spacing) and/or the width of the transects (buf_halfwidth)
alaska.prune_network()
alaska.assign_flow_directions()
alaska.to_geovectors('all')
```

And when we look at the generated mesh in QGIS, it looks like this:
![image](https://user-images.githubusercontent.com/14874485/211094757-7aee7eac-2db0-43bb-bc5d-ddf19ec1fb36.png)

@hcamkerr You will need to fetch the latest version of RivGraph from this repository to have this new functionality. We can't really provide too much support for that, but one way that might work would be to uninstall RivGraph from your environment, clone this repo, then do a "live install" via `pip install -e .` in the directory where you've cloned the repo (i.e. where `setup.py`) lives.

Also, please hold on because I will need to see if your other issue requires any changes to the codebase. I'll try to finish that one later today, or this weekend for sure.

@elbeejay I am sure that these edits will break some of the tests because I had to change some of the input and output arguments to some functions. I'll fix that later, but for now the tests should be failing.

**Comment by jonschwenk** [comment] 2023-01-06 20:39
Edits above refer to https://github.com/VeinsOfTheEarth/RivGraph/commit/80986da79cbe89dd537e8e04365e3a2156fcf866

**Comment by jonschwenk** [comment] 2023-01-06 21:08
Ok, the second issue (ESRI mask) is a bug? in GeoPandas/pyproj.

RivGraph just copies the CRS (coordinate reference system) of the input mask to the output coordinates. My testing indicates that the correct CRS is being carried through properly and being assigned properly, but GeoPandas is outputting a CRS of EPSG:4326. To double-check this, I edited the `centerline_to_geovector` function as such:

```
def centerline_to_geovector(cl, crs, path_export):

    # Put points into shapely LineString
    if type(cl) is not LineString:
        cl = LineString(zip(cl[0], cl[1]))

    # Geopandas dataframe
    cl_df = gpd.GeoDataFrame(geometry=[cl])
    cl_df.set_crs(crs, inplace=True)
    cl_df = cl_df.to_crs('epsg:4326') # This is new -- reprojecting to EPSG 4326

    # Save
    cl_df.to_file(path_export, driver=get_driver(path_export))

```
and when I look at the results, the output centerline falls exactly where it should:
![image](https://user-images.githubusercontent.com/14874485/211099628-2411a494-71ce-42ac-ab27-bc8d442ba4ac.png)
(in blue)

However, if I don't reproject the centerline to PESG:4326, GeoPandas exports it as 4326 anyway (but without actually reprojecting it). This results in a centerline whose coordinates are in the CRS you provided (ESRI:XXXXX) but whose file _thinks_ they are ESPG:4326.

I don't see any way for RivGraph to fix this since it appears to be a GeoPandas bug--I suggest opening an issue there to help them fix it, but in the meantime the unsatisfying solution would be "use the UTM mask." (and in general avoid uncommon CRS's like ESRI's or other custom projections).

I think that wraps it up--I was unable to reproduce the errors you showed, so I'm not exactly sure what's going on. If you need more help, you will need to provide a MRE (minimum reproducible example that includes all the code needed to reproduce your error) and I might be able to give you more insight. But the code I shared above works with the repo-version of RivGraph, so clone it and run it as above and you should have no problems! Closing for now, will reopen if you have more questions @hcamkerr

**Closed by jonschwenk** 2023-01-06 21:08 UTC

**Comment by hcamkerr** [comment] 2023-01-09 13:05
Thank you so much @jonschwenk, I will try these edits and see if I have any luck this time!
